In [28]:
import numpy as np

In [29]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))
#
%time for _ in range(10): my_arr2 = my_arr * 2 #nmpy_arr
#
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]    

CPU times: user 13.1 ms, sys: 5.27 ms, total: 18.3 ms
Wall time: 18.4 ms
CPU times: user 718 ms, sys: 184 ms, total: 902 ms
Wall time: 903 ms


In [30]:
nd_2darr = np.array([[1,2,3],[4,5,6]])
print(nd_2darr.shape)
print(nd_2darr.ndim)

(2, 3)
2


In [31]:
simple_nd_linear_arr = np.arange(20)
simple_nd_linear_arr.shape

(20,)

In [32]:
random_dataset = np.array([[np.random.randn(10), np.random.randn(10)]])
print(f"Shape:{str(random_dataset.shape)}")
random_dataset

Shape:(1, 2, 10)


array([[[-1.13257641,  0.81326634, -1.29122123, -1.01517382,
         -0.31130843,  0.47387978, -1.34229655,  0.14622419,
          0.41981044,  2.14949461],
        [-1.10137818, -0.92783821, -0.74870755, -0.73051223,
          0.63199303, -0.69693124,  1.0211943 ,  1.12603353,
          0.37656485, -0.36736993]]])

## Slicing Arrays.

In [33]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [34]:
arr_2d[0] = np.zeros(len(arr_2d[0]))
arr_2d

array([[0, 0, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
# matrix of ones using ones_like function.
np.ones_like(np.arange(10))

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [36]:
# matrix of ones using ones function.
ones_arr = np.ones((10),dtype=np.float32)
ones_arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [37]:
ones_arr_v2 = np.ones(np.arange(10).shape, dtype=np.int32) #  np.ones function needs a shape.
ones_arr_v2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [38]:
# arr_using_np_asarray = np.asarray([1,2,3,4])
arr_using_np_asarray = np.asarray(np.arange(1,10))
arr_using_np_asarray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr_using_np_asarray = np.asarray([x for x in range(1,10)])
arr_using_np_asarray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
old_arr = np.arange(1,15,2)
print(f"Old Array:{str(old_arr)}")
# new_my_arr = np.empty(old_arr)
# new_my_arr = np.empty((2,2))
new_my_arr = np.empty_like((2,2))
new_my_arr

Old Array:[ 1  3  5  7  9 11 13]


array([-4610227203241920180, -4617391478579344018])

In [41]:
full_np_arr = np.full((2,2), 2.0)
full_np_arr

array([[2., 2.],
       [2., 2.]])

In [42]:
square_matrix = np.array([[2,2],[2,2]])
square_matrix.shape

(2, 2)

In [43]:
square_matrix = np.full_like((np.array([[1,2],[2,2]])),1.0, dtype=np.int32)
print(square_matrix)
# change type
square_matrix.astype(dtype=np.float32)

[[1 1]
 [1 1]]


array([[1., 1.],
       [1., 1.]], dtype=float32)

In [44]:
# Identity Matrix
identity_matrix = np.identity(4, dtype=np.int32)
print(identity_matrix[0].dtype)
identity_matrix

int32


array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

In [45]:
# tranpose a matrix
to_be_transposed_arr = np.random.randn(2,3)
print(to_be_transposed_arr)
print()
# print(to_be_transposed_arr.T)
print(to_be_transposed_arr.transpose())
np.dot(to_be_transposed_arr.T,to_be_transposed_arr)

[[-0.10360743  0.21062246  0.90010578]
 [-1.70672323  0.18877124  1.0397476 ]]

[[-0.10360743 -1.70672323]
 [ 0.21062246  0.18877124]
 [ 0.90010578  1.0397476 ]]


array([[ 2.92363869, -0.34400232, -1.86781903],
       [-0.34400232,  0.0799964 ,  0.38585694],
       [-1.86781903,  0.38585694,  1.89126549]])

In [46]:
even_numbers = np.array([2,4,6,8,10])
odd_numbers =  np.array([1,3,5,7,9])
even_numbers @ odd_numbers # Dot Product of all elements.

190

In [47]:
np.dot(even_numbers, odd_numbers)

190

In [48]:
even_numbers * odd_numbers 

array([ 2, 12, 30, 56, 90])

In [49]:
np.multiply(even_numbers, odd_numbers)

array([ 2, 12, 30, 56, 90])

In [115]:
arr_sample_transpose_setting_axis = np.arange(16).reshape((2, 2, 4))
print(arr_sample_transpose_setting_axis)
print()
print(arr_sample_transpose_setting_axis.shape)
print()
result_trasnpose = arr_sample_transpose_setting_axis.transpose(1,0,2)
result_trasnpose_2 = arr_sample_transpose_setting_axis.transpose()
# print(result_trasnpose.shape)
print(result_trasnpose)
print()
print(result_trasnpose_2.shape)
print(result_trasnpose_2.ndim)
#
# Strides of an array.
print(f"Strides: {result_trasnpose.strides}")
print()
result_trasnpose_2

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]

(2, 2, 4)

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]

(4, 2, 2)
3
Strides: (32, 64, 8)



array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [87]:
x = np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [88]:
x.transpose()

array([[0, 2],
       [1, 3]])

In [97]:
arr_1d = np.arange(1,10)
arr_1d.transpose()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])