In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))
#
%time for _ in range(10): my_arr2 = my_arr * 2 #nmpy_arr
#
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]    

CPU times: user 10.7 ms, sys: 3.15 ms, total: 13.9 ms
Wall time: 14.1 ms
CPU times: user 708 ms, sys: 147 ms, total: 855 ms
Wall time: 857 ms


In [3]:
nd_2darr = np.array([[1,2,3],[4,5,6]])
print(nd_2darr.shape)
print(nd_2darr.ndim)

(2, 3)
2


In [4]:
simple_nd_linear_arr = np.arange(20)
simple_nd_linear_arr.shape

(20,)

In [5]:
random_dataset = np.array([[np.random.randn(10), np.random.randn(10)]])
print(f"Shape:{str(random_dataset.shape)}")
random_dataset

Shape:(1, 2, 10)


array([[[-0.79191081, -0.7967472 ,  1.01024666,  0.32255435,
          1.19253457,  0.46298509, -0.73982401,  0.28219691,
         -0.87875305,  1.05561244],
        [-0.0577329 ,  0.35582284,  0.07341766, -0.23367342,
          0.17572781,  0.52073597, -0.75561066, -0.0646454 ,
         -0.21775665, -0.13322055]]])

## Slicing Arrays.

In [6]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d.shape)
arr_2d[1:,1:]

(3, 3)


array([[5, 6],
       [8, 9]])

In [7]:
arr_2d[0] = np.zeros(len(arr_2d[0]))
arr_2d

array([[0, 0, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# matrix of ones using ones_like function.
np.ones_like(np.arange(10))

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [10]:
# matrix of ones using ones function.
ones_arr = np.ones((10),dtype=np.float32)
ones_arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [11]:
ones_arr_v2 = np.ones(np.arange(10).shape, dtype=np.int32) #  np.ones function needs a shape.
ones_arr_v2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [12]:
# arr_using_np_asarray = np.asarray([1,2,3,4])
arr_using_np_asarray = np.asarray(np.arange(1,10))
arr_using_np_asarray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr_using_np_asarray = np.asarray([x for x in range(1,10)])
arr_using_np_asarray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
old_arr = np.arange(1,15,2)
print(f"Old Array:{str(old_arr)}")
# new_my_arr = np.empty(old_arr)
# new_my_arr = np.empty((2,2))
new_my_arr = np.empty_like((2,2))
new_my_arr

Old Array:[ 1  3  5  7  9 11 13]


array([-9093133594791772160,           4534583192])

In [15]:
full_np_arr = np.full((2,2), 2.0)
full_np_arr

array([[2., 2.],
       [2., 2.]])

In [16]:
square_matrix = np.array([[2,2],[2,2]])
square_matrix.shape

(2, 2)

In [17]:
square_matrix = np.full_like((np.array([[1,2],[2,2]])),1.0, dtype=np.int32)
print(square_matrix)
# change type
square_matrix.astype(dtype=np.float32)

[[1 1]
 [1 1]]


array([[1., 1.],
       [1., 1.]], dtype=float32)

In [18]:
# Identity Matrix
identity_matrix = np.identity(4, dtype=np.int32)
print(identity_matrix[0].dtype)
identity_matrix

int32


array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

In [19]:
# tranpose a matrix
to_be_transposed_arr = np.random.randn(2,3)
print(to_be_transposed_arr)
print()
# print(to_be_transposed_arr.T)
print(to_be_transposed_arr.transpose())
np.dot(to_be_transposed_arr.T,to_be_transposed_arr)

[[ 0.08934208 -2.13065584  0.12572427]
 [ 0.65893761  1.06529601 -0.25662449]]

[[ 0.08934208  0.65893761]
 [-2.13065584  1.06529601]
 [ 0.12572427 -0.25662449]]


array([[ 0.44218078,  0.51160638, -0.15786706],
       [ 0.51160638,  5.67454987, -0.5412562 ],
       [-0.15786706, -0.5412562 ,  0.08166272]])

In [20]:
even_numbers = np.array([2,4,6,8,10])
odd_numbers =  np.array([1,3,5,7,9])
even_numbers @ odd_numbers # Dot Product of all elements.

190

In [21]:
np.dot(even_numbers, odd_numbers)

190

In [22]:
even_numbers * odd_numbers 

array([ 2, 12, 30, 56, 90])

In [23]:
np.multiply(even_numbers, odd_numbers)

array([ 2, 12, 30, 56, 90])

In [24]:
arr_sample_transpose_setting_axis = np.arange(16).reshape((2, 2, 4))
# arr_sample_transpose_setting_axis = np.arange(8).reshape((2, 2, 2))
#
print(arr_sample_transpose_setting_axis)
print()
print(arr_sample_transpose_setting_axis.shape)
print()
result_trasnpose = arr_sample_transpose_setting_axis.transpose(1,0,2)
result_trasnpose_2 = arr_sample_transpose_setting_axis.transpose()
# print(result_trasnpose.shape)
print(result_trasnpose)
print()
print(result_trasnpose_2.shape)
print(result_trasnpose_2.ndim)
#
# Strides of an array.
print(f"Strides: {result_trasnpose.strides}")
print()
result_trasnpose_2

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]

(2, 2, 4)

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]

(4, 2, 2)
3
Strides: (32, 64, 8)



array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [25]:
# Swapaxes
swapped_result = result_trasnpose_2.swapaxes(0,2)
print(f"Shape: {swapped_result.shape}")
swapped_result

Shape: (2, 2, 4)


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [26]:
x = np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [27]:
x.transpose()

array([[0, 2],
       [1, 3]])

In [28]:
arr_1d = np.arange(1,10)
arr_1d.transpose()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
linear_arr = np.array([[1,2,3]])
np.swapaxes(linear_arr,0,1)

array([[1],
       [2],
       [3]])

In [30]:
dimension_testee = np.arange(1,10, dtype=np.float16)
dimension_testee

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float16)

## Arthematic Operations.

In [31]:
np_arr1 = np.arange(1,11).reshape(2,5)
np_arr2 = np.arange(11,21).reshape(2,5)
# np_arr2 = np.arange(11,21).reshape(2,5).swapaxes(1,0) #ValueError: operands could not be broadcast together with shapes (2,5) (5,2) 
#
print(np_arr1)
print()
print(np_arr2)
print()
# Addition.
print("Addition")
result_arr_add = np_arr1 + np_arr2
print(result_arr)
result_arr_sub = np_arr1 - np_arr2
print("Subtraction")
print(result_arr_sub)
result_arr_mul = np_arr1 * np_arr2
print("Multiplication")
print(result_arr_sub)
result_arr_div = np_arr1 / np_arr2
print("Divison")
print(result_arr_div)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[11 12 13 14 15]
 [16 17 18 19 20]]

Addition


NameError: name 'result_arr' is not defined

In [32]:
sliced_src_arr = np.arange(1,11)
print("Original Source")
print(sliced_src_arr)
print()
print(slicing_src_arr.shape)
print(slicing_src_arr.ndim)
#
copy_sliced_src_arr = sliced_src_arr[:]
print(copy_sliced_src_arr)
copy_sliced_src_arr[1:] = 12 #Assigned 
print(copy_sliced_src_arr)
sliced_src_arr

Original Source
[ 1  2  3  4  5  6  7  8  9 10]



NameError: name 'slicing_src_arr' is not defined

In [33]:
original_list = [1,2,3,4,5]
copy_list = original_list[:]
copy_list[1:] = 6
print(f"Original list: {str(original_list)}")
print(f"Copy of original list: {str(copy_list)}")
copy_list[1:]

TypeError: can only assign an iterable

In [83]:
# root_arr = np.array([np.arange(1,6),np.arange(6,11)])
root_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Main array")
print(root_arr)
print(root_arr.ndim)
sub_root_arr = root_arr[0:2,0:2]
sub_root_arr

Main array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


array([[1, 2],
       [4, 5]])

In [90]:
# Taking an entire axis.
root_arr[:,:1]

array([[1],
       [4],
       [7]])

In [94]:
print(f"Shape: {root_arr[:2, 1:].shape}")
root_arr[:2, 1:] = 0
root_arr

Shape: (2, 2)


array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [109]:
print(root_arr[2,:])
print(f"Shape: {root_arr[2,:].shape}")
print(root_arr[:,:2])
print(f"Shape: {root_arr[:,:2].shape}")
root_arr[2]

[7 8 9]
Shape: (3,)
(3, 2)


array([7, 8, 9])

## Boolean Indexing

In [110]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print()
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']

[[-0.08437254  0.92512122  0.89055991  1.10222278]
 [-0.38720895 -0.53012078 -0.03152633  1.87413422]
 [ 0.46527199 -1.1006488  -0.66995673 -1.62607132]
 [ 0.1119149   1.62432672 -0.67312463  1.99865654]
 [-0.00267264  1.29553473 -1.54277702 -0.4034446 ]
 [-0.0089247  -0.8213522   1.51407648 -0.69981808]
 [-0.45540825 -0.67915709 -0.50028423  1.45593875]]


In [111]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [116]:
# Using boolean array for Indexing an array.
print(len(data))
data[names == "Bob"]

7


array([[-0.08437254,  0.92512122,  0.89055991,  1.10222278],
       [ 0.1119149 ,  1.62432672, -0.67312463,  1.99865654]])

In [23]:
square_matrix = np.arange(11,15).reshape((2,2))
print(square_matrix[1:])
square_matrix[1,:]

[13]


array([13, 14])