In [2]:
import numpy as np

In [2]:
src_arr = np.arange(10,201,10).reshape((5,4))
src_arr

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160],
       [170, 180, 190, 200]])

## Fancy Indexing.

In [3]:
src_arr[[1,2]]

array([[ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [4]:
src_arr[np.arange(0,3)]

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [5]:
src_arr[[2,3],2]

array([110, 150])

In [6]:
src_arr[[2,4]][1]

array([170, 180, 190, 200])

In [7]:
src_arr[[-3, -4, -5]]

array([[ 90, 100, 110, 120],
       [ 50,  60,  70,  80],
       [ 10,  20,  30,  40]])

In [8]:
copy_src_arr = src_arr[[-3, -4, -5]]
copy_src_arr[0] = 10
copy_src_arr

array([[10, 10, 10, 10],
       [50, 60, 70, 80],
       [10, 20, 30, 40]])

In [9]:
# Checking main array.
src_arr

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160],
       [170, 180, 190, 200]])

In [10]:
test_copy_arr = src_arr[1:3]
test_copy_arr[0] = 20.1
test_copy_arr

array([[ 20,  20,  20,  20],
       [ 90, 100, 110, 120]])

In [11]:
src_arr

array([[ 10,  20,  30,  40],
       [ 20,  20,  20,  20],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160],
       [170, 180, 190, 200]])

In [12]:
src_arr = np.arange(10,201,10).reshape((5,4))
src_arr

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160],
       [170, 180, 190, 200]])

In [13]:
# Getting columns.
src_arr[[2,4]][:,[1,2]]

array([[100, 110],
       [180, 190]])

In [14]:
src_arr[2,:]

array([ 90, 100, 110, 120])

## Universal Functions: Fast Element-Wise Array Functions

In [15]:
data_for_computation = np.arange(1,11)
data_for_computation

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
np.sqrt(data_for_computation)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [17]:
np.exp(data_for_computation)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [18]:
np.exp((1,2,3,4)) #With tuple.

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

### Binary Universal Function.

In [20]:
arr1 = np.random.randn(10)
arr2 = np.random.randn(10)
print(arr1)
print()
print(arr2)

[-0.57239088 -0.38640938  0.88384383  1.44617161 -0.98234091  0.60761542
  0.5712474   0.65421659 -1.17317447 -0.93015313]

[-0.17029772  0.10235324  1.6619869  -0.82272229  0.27674665  0.77835601
 -1.08699276 -1.98560573 -0.61860431 -1.12245447]


In [21]:
np.maximum(arr1,arr2)

array([-0.17029772,  0.10235324,  1.6619869 ,  1.44617161,  0.27674665,
        0.77835601,  0.5712474 ,  0.65421659, -0.61860431, -0.93015313])

In [25]:
# With 2D Array.
arr1_2d = arr1.reshape(2,5)
arr2_2d = arr2.reshape(2,5)
print(arr1_2d)
print()
print(arr2_2d)
np.maximum(arr1_2d,arr2_2d)

[[-0.57239088 -0.38640938  0.88384383  1.44617161 -0.98234091]
 [ 0.60761542  0.5712474   0.65421659 -1.17317447 -0.93015313]]

[[-0.17029772  0.10235324  1.6619869  -0.82272229  0.27674665]
 [ 0.77835601 -1.08699276 -1.98560573 -0.61860431 -1.12245447]]


array([[-0.17029772,  0.10235324,  1.6619869 ,  1.44617161,  0.27674665],
       [ 0.77835601,  0.5712474 ,  0.65421659, -0.61860431, -0.93015313]])

In [ ]:
# sample_arr = np.arange(1,9)
# clone_sample_arr = sample_arr
# print("Clone")
# print(clone_sample_arr)
# clone_sample_arr[0] = 10
# sample_arr

### BROADCASTING

In [3]:
A = np.array([[1, 2, 3], [1, 2, 3]])
print(A)
b = np.array([1, 2, 3])
print(b)
C = A + b
print(C)

[[1 2 3]
 [1 2 3]]
[1 2 3]
[[2 4 6]
 [2 4 6]]
