In [2]:
import numpy as np

In [3]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))
#
%time for _ in range(10): my_arr2 = my_arr * 2 #nmpy_arr
#
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]    

CPU times: user 12.4 ms, sys: 3.76 ms, total: 16.2 ms
Wall time: 16.4 ms
CPU times: user 719 ms, sys: 160 ms, total: 879 ms
Wall time: 881 ms


In [4]:
nd_2darr = np.array([[1,2,3],[4,5,6]])
print(nd_2darr.shape)
print(nd_2darr.ndim)

(2, 3)
2


In [5]:
simple_nd_linear_arr = np.arange(20)
simple_nd_linear_arr.shape

(20,)

In [6]:
random_dataset = np.array([[np.random.randn(10), np.random.randn(10)]])
print(f"Shape:{str(random_dataset.shape)}")
random_dataset

Shape:(1, 2, 10)


array([[[ 1.5261438 ,  0.49768439,  0.31185719,  0.95811686,
          0.64959061, -1.10316661, -0.74674897, -0.04530019,
         -1.29991732,  0.82956413],
        [ 0.81975968,  0.3207362 , -0.06473569,  0.23944943,
         -0.03810766, -0.29807962, -0.6241367 , -0.25983961,
         -0.93863851, -0.13690317]]])

## Slicing Arrays.

In [7]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [8]:
arr_2d[0] = np.zeros(len(arr_2d[0]))
arr_2d

array([[0, 0, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# matrix of ones using ones_like function.
np.ones_like(np.arange(10))

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [10]:
# matrix of ones using ones function.
ones_arr = np.ones((10),dtype=np.float32)
ones_arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [11]:
ones_arr_v2 = np.ones(np.arange(10).shape, dtype=np.int32) #  np.ones function needs a shape.
ones_arr_v2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [12]:
# arr_using_np_asarray = np.asarray([1,2,3,4])
arr_using_np_asarray = np.asarray(np.arange(1,10))
arr_using_np_asarray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr_using_np_asarray = np.asarray([x for x in range(1,10)])
arr_using_np_asarray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
old_arr = np.arange(1,15,2)
print(f"Old Array:{str(old_arr)}")
# new_my_arr = np.empty(old_arr)
# new_my_arr = np.empty((2,2))
new_my_arr = np.empty_like((2,2))
new_my_arr

Old Array:[ 1  3  5  7  9 11 13]


array([-9093133594791772160,  2305843009213710232])

In [15]:
full_np_arr = np.full((2,2), 2.0)
full_np_arr

array([[2., 2.],
       [2., 2.]])

In [16]:
square_matrix = np.array([[2,2],[2,2]])
square_matrix.shape

(2, 2)

In [17]:
square_matrix = np.full_like((np.array([[1,2],[2,2]])),1.0, dtype=np.int32)
print(square_matrix)
# change type
square_matrix.astype(dtype=np.float32)

[[1 1]
 [1 1]]


array([[1., 1.],
       [1., 1.]], dtype=float32)

In [18]:
# Identity Matrix
identity_matrix = np.identity(4, dtype=np.int32)
print(identity_matrix[0].dtype)
identity_matrix

int32


array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

In [19]:
# tranpose a matrix
to_be_transposed_arr = np.random.randn(2,3)
print(to_be_transposed_arr)
print()
# print(to_be_transposed_arr.T)
print(to_be_transposed_arr.transpose())
np.dot(to_be_transposed_arr.T,to_be_transposed_arr)

[[-0.12761696  0.23016278  0.56565069]
 [-0.60556433  0.34032692 -0.4711868 ]]

[[-0.12761696 -0.60556433]
 [ 0.23016278  0.34032692]
 [ 0.56565069 -0.4711868 ]]


array([[ 0.38299424, -0.23546251,  0.2131473 ],
       [-0.23546251,  0.16879732, -0.03016582],
       [ 0.2131473 , -0.03016582,  0.5419777 ]])

In [20]:
even_numbers = np.array([2,4,6,8,10])
odd_numbers =  np.array([1,3,5,7,9])
even_numbers @ odd_numbers # Dot Product of all elements.

190

In [21]:
np.dot(even_numbers, odd_numbers)

190

In [22]:
even_numbers * odd_numbers 

array([ 2, 12, 30, 56, 90])

In [23]:
np.multiply(even_numbers, odd_numbers)

array([ 2, 12, 30, 56, 90])

In [26]:
arr_sample_transpose_setting_axis = np.arange(16).reshape((2, 2, 4))
# arr_sample_transpose_setting_axis = np.arange(8).reshape((2, 2, 2))
#
print(arr_sample_transpose_setting_axis)
print()
print(arr_sample_transpose_setting_axis.shape)
print()
result_trasnpose = arr_sample_transpose_setting_axis.transpose(1,0,2)
result_trasnpose_2 = arr_sample_transpose_setting_axis.transpose()
# print(result_trasnpose.shape)
print(result_trasnpose)
print()
print(result_trasnpose_2.shape)
print(result_trasnpose_2.ndim)
#
# Strides of an array.
print(f"Strides: {result_trasnpose.strides}")
print()
result_trasnpose_2

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]

(2, 2, 4)

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]

(4, 2, 2)
3
Strides: (32, 64, 8)



array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [40]:
# Swapaxes
swapped_result = result_trasnpose_2.swapaxes(0,2)
print(f"Shape: {swapped_result.shape}")
swapped_result

Shape: (2, 2, 4)


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [25]:
x = np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [88]:
x.transpose()

array([[0, 2],
       [1, 3]])

In [97]:
arr_1d = np.arange(1,10)
arr_1d.transpose()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
linear_arr = np.array([[1,2,3]])
np.swapaxes(linear_arr,0,1)

array([[1],
       [2],
       [3]])

In [45]:
dimension_testee = np.arange(1,10, dtype=np.float16)
dimension_testee

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float16)

## Arthematic Operations.

In [15]:
np_arr1 = np.arange(1,11).reshape(2,5)
np_arr2 = np.arange(11,21).reshape(2,5)
# np_arr2 = np.arange(11,21).reshape(2,5).swapaxes(1,0) #ValueError: operands could not be broadcast together with shapes (2,5) (5,2) 
#
print(np_arr1)
print()
print(np_arr2)
print()
# Addition.
print("Addition")
result_arr_add = np_arr1 + np_arr2
print(result_arr)
result_arr_sub = np_arr1 - np_arr2
print("Subtraction")
print(result_arr_sub)
result_arr_mul = np_arr1 * np_arr2
print("Multiplication")
print(result_arr_sub)
result_arr_div = np_arr1 / np_arr2
print("Divison")
print(result_arr_div)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[11 16]
 [12 17]
 [13 18]
 [14 19]
 [15 20]]

Addition


ValueError: operands could not be broadcast together with shapes (2,5) (5,2) 