In [22]:
# Class #1: 21/Sep/2019 
import numpy as np

In [23]:
my_list = %time list(range(20))
type(my_list)

CPU times: user 5 µs, sys: 0 ns, total: 5 µs
Wall time: 7.87 µs


list

In [24]:
numpy_arr = %time np.arange(20)
type(numpy_arr)

CPU times: user 15 µs, sys: 3 µs, total: 18 µs
Wall time: 22.6 µs


numpy.ndarray

In [25]:
np_nums = np.linspace(1,20 , num=20)
np_nums

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [26]:
data = np.random.randn(2, 2)
data #2D Numpy Array.

array([[-0.81676039,  0.39812056],
       [ 1.60281921,  0.33771557]])

In [27]:
#Mathematical Operation with data.
data * 2

array([[-1.63352078,  0.79624112],
       [ 3.20563842,  0.67543114]])

In [28]:
#Adding Numpy array with numpy array.
result_data = data + data
result_data

array([[-1.63352078,  0.79624112],
       [ 3.20563842,  0.67543114]])

In [29]:
# Check dimension of numpy array.
data.ndim

2

In [30]:
data_3d = np.random.randn(2, 3, 4, 2)
data_3d

array([[[[-1.06323085, -1.20210514],
         [ 0.72047191, -1.44889646],
         [-1.09515776, -0.73760756],
         [ 1.01909534, -0.72927983]],

        [[-0.81684823, -0.08236229],
         [ 1.87502416, -0.0954273 ],
         [ 1.83451429,  0.15684731],
         [-1.30860431,  0.46256685]],

        [[ 0.23692229, -1.35087805],
         [ 0.26069887, -1.0195038 ],
         [ 1.89402316, -0.80432504],
         [ 0.59022469,  0.34129596]]],


       [[[-1.574361  ,  1.07268341],
         [-0.41581665, -1.44692289],
         [-1.42557968, -0.06119538],
         [-0.87924683,  0.61100171]],

        [[-1.26436756,  0.64252805],
         [-0.96972486,  0.11601664],
         [ 1.27514712,  0.46645376],
         [-0.8241171 , -0.42591597]],

        [[ 1.15263134, -0.35507576],
         [ 1.09713575,  0.6114799 ],
         [-1.0308019 ,  0.25089155],
         [-1.08871962,  0.3890638 ]]]])

In [31]:
multiply_data = data * data
multiply_data

array([[0.66709753, 0.15849998],
       [2.56902942, 0.11405181]])

In [32]:
data1 = np.random.randn(2,3)
data1

array([[-1.02070415,  0.0587624 ,  0.15835535],
       [ 1.28874935, -1.80067971, -0.20889731]])

In [33]:
data @ data1 #matrix multiplication.

array([[ 1.34674833, -0.76488242, -0.2125047 ],
       [-1.2007735 , -0.51393208,  0.18326713]])

In [34]:
np.dot(data,data1)

array([[ 1.34674833, -0.76488242, -0.2125047 ],
       [-1.2007735 , -0.51393208,  0.18326713]])

In [35]:
data1.dot(data)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [36]:
data.dot(data1)

array([[ 1.34674833, -0.76488242, -0.2125047 ],
       [-1.2007735 , -0.51393208,  0.18326713]])

In [37]:
# list of zeroes.
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [38]:
# list of ones.
np.ones(5)

array([1., 1., 1., 1., 1.])

In [39]:
np.empty(1)

array([1.])

In [40]:
print(data1.dtype)
np.ones_like(data1)

float64


array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
np.ones_like(data, dtype="int8")

array([[1, 1],
       [1, 1]], dtype=int8)

In [42]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [43]:
np.full_like(data, 6, dtype="uint")

array([[6, 6],
       [6, 6]], dtype=uint64)

In [44]:
arr1 = np.array([1,2,3], dtype="float32")
arr1

array([1., 2., 3.], dtype=float32)

In [45]:
arr1.astype(dtype="int8")

array([1, 2, 3], dtype=int8)

In [46]:
arr1.astype(dtype="float32")
arr1.astype(np.int32)

array([1, 2, 3], dtype=int32)

In [51]:
dm2_arr1 = np.random.randn(2,2)
print(dm2_arr1)
print()
dm2_arr2 = np.random.randn(2,2)
print(dm2_arr2)
dm2_arr1 > dm2_arr2

[[ 0.59830466 -0.28975494]
 [ 0.89139213 -1.11999101]]
[[ 0.14423986  1.15016019]
 [-1.28584052 -0.43688936]]


array([[ True, False],
       [ True, False]])

In [63]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [65]:
arr2d[1,2]

IndexError: index 3 is out of bounds for axis 1 with size 3