# Data Cleaning and Preparation

In [1]:
import numpy as np
import pandas as pd
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [2]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [3]:
string_data[0] = None
print(string_data)

0         None
1    artichoke
2          NaN
3      avocado
dtype: object


In [4]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

## Filtering Out Missing Data

In [5]:
from numpy import nan as NA

In [6]:
data = pd.Series([1, NA, 3.5, NA, 7])

In [7]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [8]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],[NA, NA, NA], [NA, 6.5, 3.]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [9]:
cleaned = data.dropna()
cleaned

0    1    2
0  1.0  6.5  3.0

In [10]:
cleaned_how = data.dropna(how='all')
cleaned_how

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [11]:
data[4] = NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [12]:
data.dropna(axis=1,how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [13]:
data[2]

0    3.0
1    NaN
2    NaN
3    3.0
Name: 2, dtype: float64

In [14]:
df = pd.DataFrame(np.random.randn(7, 3))
df

0         1         2
0  1.382823  0.417343  2.413195
1  2.322513  0.127796 -1.528043
2 -0.150413 -2.256720 -1.330392
3 -0.909917 -0.300044 -0.916664
4  1.676808 -0.293480 -0.495151
5 -0.398313 -1.191293 -0.570502
6 -0.503044  0.766393 -0.518567

In [15]:
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA

In [16]:
df

0         1         2
0  1.382823       NaN       NaN
1  2.322513       NaN       NaN
2 -0.150413       NaN -1.330392
3 -0.909917       NaN -0.916664
4  1.676808 -0.293480 -0.495151
5 -0.398313 -1.191293 -0.570502
6 -0.503044  0.766393 -0.518567

In [17]:
df.dropna()

0         1         2
4  1.676808 -0.293480 -0.495151
5 -0.398313 -1.191293 -0.570502
6 -0.503044  0.766393 -0.518567

In [18]:
df.dropna(thresh=2)

0         1         2
2 -0.150413       NaN -1.330392
3 -0.909917       NaN -0.916664
4  1.676808 -0.293480 -0.495151
5 -0.398313 -1.191293 -0.570502
6 -0.503044  0.766393 -0.518567

## Filling In Missing Data

In [19]:
import pandas as pd

In [20]:
df.fillna(0)

0         1         2
0  1.382823  0.000000  0.000000
1  2.322513  0.000000  0.000000
2 -0.150413  0.000000 -1.330392
3 -0.909917  0.000000 -0.916664
4  1.676808 -0.293480 -0.495151
5 -0.398313 -1.191293 -0.570502
6 -0.503044  0.766393 -0.518567

In [21]:
df.fillna({1:0.5,2:0})

0         1         2
0  1.382823  0.500000  0.000000
1  2.322513  0.500000  0.000000
2 -0.150413  0.500000 -1.330392
3 -0.909917  0.500000 -0.916664
4  1.676808 -0.293480 -0.495151
5 -0.398313 -1.191293 -0.570502
6 -0.503044  0.766393 -0.518567

In [22]:
_ = df.fillna(0, inplace=True)
df

0         1         2
0  1.382823  0.000000  0.000000
1  2.322513  0.000000  0.000000
2 -0.150413  0.000000 -1.330392
3 -0.909917  0.000000 -0.916664
4  1.676808 -0.293480 -0.495151
5 -0.398313 -1.191293 -0.570502
6 -0.503044  0.766393 -0.518567

In [23]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA
df

0         1         2
0  0.845933  1.463621 -0.230432
1 -2.581242  0.344656  0.712919
2  0.309075       NaN -1.321680
3  1.476748       NaN  0.962916
4 -0.594820       NaN       NaN
5  0.429436       NaN       NaN

In [24]:
df.fillna(method='ffill')

0         1         2
0  0.845933  1.463621 -0.230432
1 -2.581242  0.344656  0.712919
2  0.309075  0.344656 -1.321680
3  1.476748  0.344656  0.962916
4 -0.594820  0.344656  0.962916
5  0.429436  0.344656  0.962916

In [25]:
df.fillna(method='ffill',limit=2)

0         1         2
0  0.845933  1.463621 -0.230432
1 -2.581242  0.344656  0.712919
2  0.309075  0.344656 -1.321680
3  1.476748  0.344656  0.962916
4 -0.594820       NaN  0.962916
5  0.429436       NaN  0.962916

In [26]:
data = pd.Series([1., NA, 3.5, NA, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [27]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

# Data Transformation

In [28]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [29]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [30]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [31]:
data['v1'] = range(7)

In [32]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [33]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [34]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [35]:
data.drop_duplicates(['k1'],keep='last')

k1  k2  v1
4  one   3   4
6  two   4   6

In [36]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
'Pastrami', 'corned beef', 'Bacon',
'pastrami', 'honey ham', 'nova lox'],
'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [37]:
lowercase = data['food'].str.lower()
lowercase

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [38]:
meat_to_animal = {
'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'nova lox': 'salmon'
}

In [39]:
data['animal'] = lowercase.map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [40]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [41]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [42]:
import numpy as np
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [43]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [44]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [45]:
data.replace({-999:np.nan,-1000:0})


0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [46]:
import numpy as np
import pandas as pd

In [47]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
index=['Ohio', 'Colorado', 'New York'],
columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [48]:
transform = lambda x: x[:4].upper()

In [49]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [50]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [51]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [52]:
data.rename(index=str.title,columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [53]:
data.rename(index={'OHIO':'dublin'},columns = {'three':'peekaboo'})

one  two  peekaboo  four
dublin    0    1         2     3
COLO      4    5         6     7
NEW       8    9        10    11

In [54]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

# Discretization and Binning

In [55]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [56]:
bins = [18, 25, 35, 60, 100]

In [57]:
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [58]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [59]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [60]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [61]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [62]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [63]:
data = np.random.rand(20)
data

array([0.14757277, 0.92231307, 0.56298566, 0.20283121, 0.50070012,
       0.4101704 , 0.06956375, 0.30466014, 0.73204408, 0.04945929,
       0.62188517, 0.72921934, 0.11454729, 0.39314882, 0.63531386,
       0.28121303, 0.12955697, 0.9204102 , 0.23471329, 0.31659028])

In [64]:
cats = pd.cut(data, 4, precision=2)
cats

[(0.049, 0.27], (0.7, 0.92], (0.49, 0.7], (0.049, 0.27], (0.49, 0.7], ..., (0.27, 0.49], (0.049, 0.27], (0.7, 0.92], (0.049, 0.27], (0.27, 0.49]]
Length: 20
Categories (4, interval[float64]): [(0.049, 0.27] < (0.27, 0.49] < (0.49, 0.7] < (0.7, 0.92]]

In [65]:
pd.value_counts(cats)

(0.049, 0.27]    7
(0.27, 0.49]     5
(0.7, 0.92]      4
(0.49, 0.7]      4
dtype: int64

In [66]:
data = np.random.randn(1000)
data[:10]

array([ 0.57527561,  0.12249265, -1.73087956,  0.82517589, -0.4159392 ,
        0.20596312, -0.68663844,  1.43787892,  2.274511  ,  0.17259427])

In [67]:
cats = pd.qcut(data,4)

In [68]:
cats

[(0.0247, 0.696], (0.0247, 0.696], (-2.699, -0.683], (0.696, 2.888], (-0.683, 0.0247], ..., (0.0247, 0.696], (-2.699, -0.683], (0.0247, 0.696], (-0.683, 0.0247], (-2.699, -0.683]]
Length: 1000
Categories (4, interval[float64]): [(-2.699, -0.683] < (-0.683, 0.0247] < (0.0247, 0.696] < (0.696, 2.888]]

In [69]:
pd.value_counts(cats)

(0.696, 2.888]      250
(0.0247, 0.696]     250
(-0.683, 0.0247]    250
(-2.699, -0.683]    250
dtype: int64

In [70]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(0.0247, 1.262], (0.0247, 1.262], (-2.699, -1.258], (0.0247, 1.262], (-1.258, 0.0247], ..., (0.0247, 1.262], (-2.699, -1.258], (0.0247, 1.262], (-1.258, 0.0247], (-1.258, 0.0247]]
Length: 1000
Categories (4, interval[float64]): [(-2.699, -1.258] < (-1.258, 0.0247] < (0.0247, 1.262] < (1.262, 2.888]]

# Detecting and Filtering Outliers

In [71]:
import pandas as pd
import numpy as np
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.026859    -0.009498    -0.055612     0.038987
std       0.988474     1.012785     0.995126     1.032126
min      -2.681896    -3.729458    -3.812624    -4.047617
25%      -0.697047    -0.688886    -0.743416    -0.629425
50%      -0.042040    -0.019943    -0.038841     0.014973
75%       0.619151     0.678680     0.626802     0.718255
max       3.603607     3.200271     3.290092     3.095755

In [72]:
col = data[2]

In [73]:
col[np.abs(col)>2]

65    -2.421686
109    2.012902
143   -2.442362
150   -2.195095
156    2.686549
169    2.130292
212   -2.014305
224    2.148934
283   -2.046772
325   -2.054545
333   -2.125127
341    2.048065
375   -2.022479
387    2.132662
400   -2.288392
414   -2.393447
426    2.871827
488    2.088559
512   -2.290275
534    2.088291
535    2.216070
562    2.717033
578   -3.037665
598   -2.044040
645    2.190893
655    2.338700
666    3.290092
679   -2.183679
680    2.154819
689   -2.093470
693   -2.905008
695    2.011419
696   -2.446717
745   -2.331248
791    2.474527
793    2.045946
837   -2.253127
915   -2.791133
920   -2.625401
941   -2.014029
942   -2.509097
953   -3.812624
977   -2.077453
980    2.354881
Name: 2, dtype: float64

In [74]:
data[(np.abs(data)>3)]

0   1   2   3
0   NaN NaN NaN NaN
1   NaN NaN NaN NaN
2   NaN NaN NaN NaN
3   NaN NaN NaN NaN
4   NaN NaN NaN NaN
..   ..  ..  ..  ..
995 NaN NaN NaN NaN
996 NaN NaN NaN NaN
997 NaN NaN NaN NaN
998 NaN NaN NaN NaN
999 NaN NaN NaN NaN

[1000 rows x 4 columns]

In [75]:
data[(np.abs(data)>3)][22:23]

0   1   2   3
22 NaN NaN NaN NaN

In [76]:
data[(np.abs(data)>3).any(1)]

0         1         2         3
51   3.271312 -1.501543 -0.648928  0.830664
98   1.668392 -3.329757 -0.847093  1.676768
292 -0.211268 -3.037467  0.907592  0.589039
412 -0.836802 -0.920494 -0.468858  3.095755
450 -0.306088  3.200271  1.100744  1.143874
578  1.147548  0.839521 -3.037665 -0.066935
641 -1.413179 -0.182105  0.294744 -3.116001
654  3.603607  0.929232 -0.507389  0.606163
666 -0.719498  0.207225  3.290092 -1.058797
697  3.576489  0.300809 -0.630821  0.570641
893  0.780280  0.540926  1.038443 -4.047617
953 -0.520566  1.086731 -3.812624  0.682179
984  2.052395 -0.041365  0.463130 -3.063431
985  1.209536 -3.729458 -0.527511 -0.624370

In [77]:
np.sign(data) * 3

0    1    2    3
0    3.0  3.0 -3.0 -3.0
1   -3.0  3.0 -3.0 -3.0
2    3.0 -3.0 -3.0 -3.0
3    3.0  3.0  3.0 -3.0
4    3.0  3.0  3.0 -3.0
..   ...  ...  ...  ...
995 -3.0 -3.0 -3.0  3.0
996 -3.0  3.0 -3.0  3.0
997  3.0  3.0  3.0 -3.0
998  3.0 -3.0 -3.0 -3.0
999  3.0  3.0 -3.0  3.0

[1000 rows x 4 columns]

In [78]:
data[np.abs(data) > 3] = np.sign(data) * 3
data.head()

0         1         2         3
0  0.414899  1.272737 -1.125214 -0.480860
1 -1.032073  0.705538 -0.366418 -0.057157
2  0.606401 -0.103727 -0.461461 -1.188298
3  0.706785  0.013995  0.000484 -1.914546
4  0.140339  0.923598  0.757647 -0.077000

In [79]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.028311    -0.008602    -0.055052     0.040119
std       0.983622     1.008602     0.991334     1.027679
min      -2.681896    -3.000000    -3.000000    -3.000000
25%      -0.697047    -0.688886    -0.743416    -0.629425
50%      -0.042040    -0.019943    -0.038841     0.014973
75%       0.619151     0.678680     0.626802     0.718255
max       3.000000     3.000000     3.000000     3.000000

In [80]:
np.sign(data).head()

0    1    2    3
0  1.0  1.0 -1.0 -1.0
1 -1.0  1.0 -1.0 -1.0
2  1.0 -1.0 -1.0 -1.0
3  1.0  1.0  1.0 -1.0
4  1.0  1.0  1.0 -1.0

In [81]:
data.head()

0         1         2         3
0  0.414899  1.272737 -1.125214 -0.480860
1 -1.032073  0.705538 -0.366418 -0.057157
2  0.606401 -0.103727 -0.461461 -1.188298
3  0.706785  0.013995  0.000484 -1.914546
4  0.140339  0.923598  0.757647 -0.077000

In [82]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [83]:
sampler = np.random.permutation(5)
sampler

array([2, 1, 0, 4, 3])

In [84]:
df.take(sampler)

0   1   2   3
2   8   9  10  11
1   4   5   6   7
0   0   1   2   3
4  16  17  18  19
3  12  13  14  15

In [85]:
df.sample(3)

0   1   2   3
2   8   9  10  11
0   0   1   2   3
3  12  13  14  15

In [86]:
choices = pd.Series([5, 7, -1, 6, 4])
choices

0    5
1    7
2   -1
3    6
4    4
dtype: int64

In [87]:
draws = choices.sample(10,replace=True)
draws

1    7
4    4
4    4
0    5
4    4
1    7
4    4
2   -1
3    6
0    5
dtype: int64

# Computing Indicator/Dummy Variables

In [88]:
import numpy as np
import pandas as pd
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],'data1': range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [89]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [90]:
dummies = pd.get_dummies(df['key'], prefix='key')
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [91]:
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [92]:
mnames = ['movie_id', 'title', 'genres']

In [93]:
movies = pd.read_table('movies.dat', sep='::',
header=None, names=mnames)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  


In [94]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [95]:
all_genres = []
for x in movies.genres:
    all_genres.extend(x.split('|'))
genres = pd.unique(all_genres)
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [96]:
zero_matrix = np.zeros((len(movies),len(genres)))

In [97]:
dummies = pd.DataFrame(zero_matrix, columns=genres)
dummies.head()

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  Action  \
0        0.0         0.0     0.0        0.0      0.0      0.0    0.0     0.0   
1        0.0         0.0     0.0        0.0      0.0      0.0    0.0     0.0   
2        0.0         0.0     0.0        0.0      0.0      0.0    0.0     0.0   
3        0.0         0.0     0.0        0.0      0.0      0.0    0.0     0.0   
4        0.0         0.0     0.0        0.0      0.0      0.0    0.0     0.0   

   Crime  Thriller  Horror  Sci-Fi  Documentary  War  Musical  Mystery  \
0    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   
1    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   
2    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   
3    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   
4    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   

   Film-Noir  Western  
0        0.0      0.0  
1        0.0      0.0  
2        0.0      0.0  
3        0.0      0.0  
4        0.0      0.0

In [98]:
gen  = movies.genres[0]
gen.split('|')

['Animation', "Children's", 'Comedy']

In [99]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2])

In [100]:
len(movies.genres)

3883

In [101]:
for i , gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i,indices] = 1

In [102]:
dummies.head()

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  Action  \
0        1.0         1.0     1.0        0.0      0.0      0.0    0.0     0.0   
1        0.0         1.0     0.0        1.0      1.0      0.0    0.0     0.0   
2        0.0         0.0     1.0        0.0      0.0      1.0    0.0     0.0   
3        0.0         0.0     1.0        0.0      0.0      0.0    1.0     0.0   
4        0.0         0.0     1.0        0.0      0.0      0.0    0.0     0.0   

   Crime  Thriller  Horror  Sci-Fi  Documentary  War  Musical  Mystery  \
0    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   
1    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   
2    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   
3    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   
4    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   

   Film-Noir  Western  
0        0.0      0.0  
1        0.0      0.0  
2        0.0      0.0  
3        0.0      0.0  
4        0.0      0.0

In [103]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))
movies_windic.iloc[0]                            

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [104]:
movies_windic[0:5]

movie_id                               title                        genres  \
0         1                    Toy Story (1995)   Animation|Children's|Comedy   
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy   
2         3             Grumpier Old Men (1995)                Comedy|Romance   
3         4            Waiting to Exhale (1995)                  Comedy|Drama   
4         5  Father of the Bride Part II (1995)                        Comedy   

   Genre_Animation  Genre_Children's  Genre_Comedy  Genre_Adventure  \
0              1.0               1.0           1.0              0.0   
1              0.0               1.0           0.0              1.0   
2              0.0               0.0           1.0              0.0   
3              0.0               0.0           1.0              0.0   
4              0.0               0.0           1.0              0.0   

   Genre_Fantasy  Genre_Romance  Genre_Drama  ...  Genre_Crime  \
0            0.0            0.0          0.0  ...          0.0   
1            1.0            0.0          0.0  ...          0.0   
2            0.0            1.0          0.0  ...          0.0   
3            0.0            0.0          1.0  ...          0.0   
4            0.0            0.0          0.0  ...          0.0   

   Genre_Thriller  Genre_Horror  Genre_Sci-Fi  Genre_Documentary  Genre_War  \
0             0.0           0.0           0.0                0.0        0.0   
1             0.0           0.0           0.0                0.0        0.0   
2             0.0           0.0           0.0                0.0        0.0   
3             0.0           0.0           0.0                0.0        0.0   
4             0.0           0.0           0.0                0.0        0.0   

   Genre_Musical  Genre_Mystery  Genre_Film-Noir  Genre_Western  
0            0.0            0.0              0.0            0.0  
1            0.0            0.0              0.0            0.0  
2            0.0            0.0              0.0            0.0  
3            0.0            0.0              0.0            0.0  
4            0.0            0.0              0.0            0.0  

[5 rows x 21 columns]

In [105]:
np.random.seed(12345)
values = np.random.rand(10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [106]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [107]:
pd.cut(values, bins)

[(0.8, 1.0], (0.2, 0.4], (0.0, 0.2], (0.2, 0.4], (0.4, 0.6], (0.4, 0.6], (0.8, 1.0], (0.6, 0.8], (0.6, 0.8], (0.6, 0.8]]
Categories (5, interval[float64]): [(0.0, 0.2] < (0.2, 0.4] < (0.4, 0.6] < (0.6, 0.8] < (0.8, 1.0]]

In [108]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

# String Manipulation

In [109]:
val = 'a,b, guido'
val.split(',')


['a', 'b', ' guido']

In [110]:
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [111]:
import numpy as np
import pandas as pd

In [112]:
first,second, third = pieces


In [113]:
first + '::' + second + '::' + third

'a::b::guido'

In [114]:
first + ',' + second + '::' + third

'a,b::guido'

In [115]:
'::'.join(pieces)

'a::b::guido'

In [116]:
'guido' in val

True

In [117]:
val.index(',')

1

In [118]:
val.find(':')

-1

In [119]:
val.count(',')

2

In [120]:
val.replace(',',"::")

'a::b:: guido'

In [121]:
val.replace(',','')

'ab guido'

In [122]:
import re
text = "foo bar\t baz \tqux"
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [123]:
regex = re.compile('\s+')

In [124]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [125]:
regex.findall(text)

[' ', '\t ', ' \t']

In [126]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'
# re.IGNORECASE makes the regex case-insensitive
regex = re.compile(pattern, flags=re.IGNORECASE)

In [127]:
regex.split(text)

['Dave ', '\nSteve ', '\nRob ', '\nRyan ', '\n']

In [128]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [129]:
m = regex.search(text)
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [130]:
text[m.start():m.end()]

'dave@google.com'

In [131]:
# regex.match returns None, as it only will match if the pattern occurs at the start of the
# string:
print(regex.match(text))

None


In [132]:
# Relatedly, sub will return a new string with occurrences of the pattern replaced by the
# a new string:
print(regex.sub('REDACTED',text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [133]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'
regex = re.compile(pattern, flags=re.IGNORECASE)

In [134]:
m = regex.match('wesm@bright.net')
m

<re.Match object; span=(0, 15), match='wesm@bright.net'>

In [135]:
m.groups()

('wesm', 'bright', 'net')

In [136]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [137]:
print(regex.sub(r'Username:\1, Domain:\2, Suffix:\3',text))

Dave Username:dave, Domain:google, Suffix:com
Steve Username:steve, Domain:gmail, Suffix:com
Rob Username:rob, Domain:gmail, Suffix:com
Ryan Username:ryan, Domain:yahoo, Suffix:com



# Vectorized String Functions in pandas

In [138]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com','Rob': 'rob@gmail.com', 'Wes': np.nan}
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [139]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [140]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [141]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [142]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [143]:
matches = data.str.match(pattern, flags=re.IGNORECASE)
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [144]:
matches.str.get(1)

AttributeError: Can only use .str accessor with string values!

In [ ]:
matches.str[0]

In [ ]:
data.str[:5]