In [2]:
import numpy as np

In [3]:
import numpy as np
my_arr = np.arange(1000)
print(my_arr)
print()
my_list = list(range(1000))
print(my_list)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [4]:
# Performance assesement.
%time for _ in range(10): my_arr2 = my_arr * 2
#
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]


CPU times: user 58 µs, sys: 44 µs, total: 102 µs
Wall time: 89.2 µs
CPU times: user 641 µs, sys: 15 µs, total: 656 µs
Wall time: 659 µs


In [5]:
# Creating ndarray.
# first_arr = np.array([1,"2"])
# first_arr = np.array([1,2])
first_arr = np.array([1,"2",True])
print(f"Data Type: {first_arr.dtype}")
first_arr

Data Type: <U21


array(['1', '2', 'True'], dtype='<U21')

In [6]:
# Try to create ndarray with another ndarray.
sample_arr = np.array(np.array(np.arange(1,11)))
sample_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
# Generate zeroes.
np.zeros((2,2),dtype=np.int8)

array([[0, 0],
       [0, 0]], dtype=int8)

In [8]:
# Generate ones.
np.ones((2,2),dtype=np.int8)

array([[1, 1],
       [1, 1]], dtype=int8)

In [9]:
#Unsigned data type demo.
arr = np.array([1,-2,3,4,-5],dtype=np.uint8)
arr

array([  1, 254,   3,   4, 251], dtype=uint8)

In [10]:
# Converting type of ndarray.
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(f"Current type: {arr.dtype}")
arr.astype(np.int8)

Current type: float64


array([ 3, -1, -2,  0, 12, 10], dtype=int8)

In [15]:
arr = np.array([1.22224, 2.1113, 3.2224])
arr.astype(np.string_)

array([b'1.22224', b'2.1113', b'3.2224'], dtype='|S32')

In [16]:
arr = np.array([1.22224, 2.1113, 3.2224])
arr.astype(np.string)

AttributeError: module 'numpy' has no attribute 'string'

In [17]:
arr = np.array([1.22224, 2.1113, 3.2224])
arr.astype(np.string_type)

AttributeError: module 'numpy' has no attribute 'string_type'

In [23]:
my_str = np.array("Raise Error for me.") # Does not raise exception.
get_chars = [char for my_char in my_str]
get_chars

TypeError: iteration over a 0-d array

In [27]:
# Referenced type of another dtype array.
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
print(int_array.astype(calibers.dtype))
print()
print("Old array.")
print(int_array)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

Old array.
[0 1 2 3 4 5 6 7 8 9]


In [28]:
arr = np.array([np.arange(1,5),np.arange(11,15)])
arr * arr 

array([[  1,   4,   9,  16],
       [121, 144, 169, 196]])

In [29]:
arr = np.array([np.arange(1,5),np.arange(11,15)])
arr + arr 

array([[ 2,  4,  6,  8],
       [22, 24, 26, 28]])

In [30]:
arr = np.array([np.arange(1,5),np.arange(11,15)])
arr - arr 

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [31]:
arr = np.array([np.arange(1,5),np.arange(11,15)])
arr / arr 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
# Broadcasting happens here.
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([11,12,13])
arr1 + arr2

array([[12, 14, 16],
       [15, 17, 19]])

In [35]:
1 / arr

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857]])

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2 > arr